/*
 * Generated by erpcgen 1.10.0 on Sun May 28 20:10:47 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_bbcar_control_h_)
#define _bbcar_control_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief BBCarService identifiers */
enum _BBCarService_ids
{
    kBBCarService_service_id = 1,
    kBBCarService_stop_id = 1,
    kBBCarService_goStraight_id = 2,
    kBBCarService_turn_id = 3,
    kBBCarService_ctl_mode_id = 4,
    kBBCarService_RemoteControlAction_id = 5,
    kBBCarService_RemoteTuneSpeed_id = 6,
    kBBCarService_RemoteShowSpeed_id = 7,
    kBBCarService_RemoteShowPattern_id = 8,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name BBCarService
//@{
void stop(uint8_t cars);

void goStraight(uint8_t cars, int32_t speed);

void turn(uint8_t cars, int32_t speed, double factor);

void ctl_mode(void);

void RemoteControlAction(uint8_t mode, int32_t value, double factor);

void RemoteTuneSpeed(double max, double min);

void RemoteShowSpeed(void);

void RemoteShowPattern(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _bbcar_control_h_
